SOURCES += app/View/main_window/main_window.py \
        app/View/setting_interface/setting_interface.py \
        app/common/thread/crawl_meta_data_thread.py \
        app/components/dialog_box/dialog.py \
        app/View/navigation_interface/navigation_widget.py \
        app/View/navigation_interface/navigation_menu.py \
        app/View/navigation_interface/search_line_edit.py \
        app/View/navigation_interface/navigation_button.py \
        app/View/navigation_interface/navigation_bar.py \
        app/View/navigation_interface/navigation_interface.py \
        app/components/dialog_box/create_playlist_dialog.py \
        app/components/dialog_box/rename_playlist_dialog.py \
        app/components/title_bar/title_bar.py \
        app/View/playlist_card_interface/playlist_card_interface.py \
        app/View/playlist_card_interface/selection_mode_bar.py \
        app/components/playlist_card/playlist_card.py \
        app/components/widgets/menu.py \
        app/View/playlist_interface/playlist_info_bar.py \
        app/View/playlist_interface/playlist_interface.py \
        app/View/playlist_interface/song_list_widget.py \
        app/View/playlist_interface/selection_mode_bar.py \
        app/View/album_interface/album_info_bar.py \
        app/View/album_interface/album_interface.py \
        app/View/album_interface/song_list_widget.py \
        app/View/album_interface/selection_mode_bar.py \
        app/View/singer_interface/singer_info_bar.py \
        app/View/singer_interface/singer_interface.py \
        app/View/singer_interface/selection_mode_bar.py \
        app/View/play_bar/play_bar_buttons.py\
        app/View/play_bar/play_bar.py \
        app/View/playing_interface/menu.py \
        app/View/playing_interface/song_card.py \
        app/View/playing_interface/song_info_card.py \
        app/View/playing_interface/playing_interface.py \
        app/View/playing_interface/selection_mode_bar.py \
        app/View/playing_interface/play_bar_buttons.py \
        app/View/playing_interface/play_bar.py \
        app/View/playing_interface/volume_slider_widget.py \
        app/View/smallest_play_interface/smallest_play_interface.py \
        app/View/my_music_interface/my_music_interface.py \
        app/View/my_music_interface/tool_bar.py \
        app/View/my_music_interface/album_tab_interface/album_card_interface.py \
        app/View/my_music_interface/album_tab_interface/selection_mode_bar.py \
        app/View/my_music_interface/song_tab_interface/song_list_widget.py \
        app/View/my_music_interface/song_tab_interface/selection_mode_bar.py \
        app/components/album_card/album_card.py \
        app/components/song_list_widget/basic_song_card.py \
        app/components/song_list_widget/song_name_card.py \
        app/components/song_list_widget/song_card.py \
        app/components/dialog_box/song_property_dialog.py \
        app/components/dialog_box/message_dialog.py \
        app/components/dialog_box/album_info_edit_dialog.py \
        app/components/dialog_box/song_info_edit_dialog.py \
        app/View/search_result_interface/search_result_interface.py \
        app/View/search_result_interface/song_group_box.py \
        app/View/search_result_interface/playlist_group_box.py \
        app/View/search_result_interface/album_group_box.py \
        app/components/system_tray_icon/system_tray_icon.py \
        app/components/video_window/video_window.py \
        app/components/widgets/tool_tip.py \
        app/components/video_window/play_bar.py \
        app/components/widgets/lyric_widget.py \
        app/components/album_card/album_card_view.py \
        app/components/album_card/album_card_base.py \
        app/components/playlist_card/playlist_card_base.py \
        app/components/playlist_card/playlist_card_view.py \
        app/common/meta_data/reader/song_info_reader.py \
        app/components/selection_mode_bar/button.py \
        app/components/selection_mode_interface/selection_mode_interface.py \
        app/View/more_search_result_interface/more_search_result_interface.py \
        app/components/singer_card/singer_card_base.py \
        app/components/singer_card/singer_card.py \
        app/View/search_result_interface/singer_group_box.py \
        app/components/settings/folder_list_setting_card.py \
        app/components/settings/setting_card.py \

TRANSLATIONS += app/resource/i18n/Groove_zh.ts \
        app/resource/i18n/Groove_hk.ts
