from .album_cover_controller import AlbumCoverController
from .album_info_controller import AlbumInfoController
from .singer_info_controller import SingerInfoController
from .song_info_controller import SongInfoController
